spring:
  datasource:
    url: jdbc:mysql://ibda.ckp1zzcl50yl.us-east-1.rds.amazonaws.com:3306/IBDA
    username: youngwoo
    password: Owe3589!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug